# Docker compose file for basic environment php stack.

# Docker compose version
version: '3'

# Docker compose services.
services:
  # Docker web service.
  web:
    # Configuration options that are applied at build time.
    build: 
      # Using Dockerfile
      context: .docker/php
      # Overrides build arguments, which are environment variables accessible only during the build process.
      args:
        - DOCKER_PHP_VERSION=7.3
        - DOCKER_APACHE_RUN_USER=pictonio
        - DOCKER_APACHE_RUN_GROUP=pictonio
        - DOCKER_APACHE_RUN_UID=1000
        - DOCKER_APACHE_RUN_GID=1001
    # Expose ports.
    ports:
      - "8080:80"
    # Link to containers in another service.
#    links:
#      - db:percona
    # Mount host paths or named volumes.
    volumes:
      # Host path volume for project docroot.
      - /data/drupal/apache:/var/www/html
      # Host path volume for php.ini configuration file.
      - ./conf/php.ini:/usr/local/etc/php/php.ini
      # Host path volume for apache default.conf file.
      - ./conf/apache.conf:/etc/apache2/sites-available/000-default.conf
      # MPM config
      - ./conf/mpm_prefork.conf:/etc/apache2/mods-available/mpm_prefork.conf
    restart: always
  # Docker db service.

# Named volumes
volumes:
  percona_data:
    driver: "local"

